name: "smpl-with-mesh-sdf-if"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  width: 512
  height: 512
  camera_distance_range: [1.5, 2.0]
  fovy_range: [15, 60]
  elevation_range: [0, 30]
  light_sample_strategy: "magic3d"
  eval_camera_distance: 3.0
  eval_fovy_deg: 40.

system_type: "with-mesh"
system:
  geometry_type: "tetrahedra-sdf-grid"
  geometry:
    # this requires generating corresponding file in load/tets
    isosurface_resolution: 256
    # e.g. "mesh:/path/to/smpl.obj"
    force_shape_init: true
    shape_init: ???
    shape_init_center_mesh: false
    shape_init_scale_mesh: false
    shape_init_params: 1.0
  
  # if the user specifies geometry_convert_from, then this is implied
  geometry_convert_inherit_texture: true

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true
    share_aug_bg: true

  composed_only: true

  # Unused except for validation/testing
  renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: cuda

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "multiview-diffusion-guidance"
  guidance:
    model_name: "sd-v2.1-base-4view"
    ckpt_path: null # path to a pre-downloaded checkpoint file (null for loading from URL)
    guidance_scale: 50.0
    min_step_percent: 0.02
    max_step_percent: 0.5
    recon_loss: true
    recon_std_rescale: 0.5

  composed_renderer_type: "with-mesh-rasterizer"
  composed_renderer:
    context_type: cuda
    mesh_path: ???
    mesh:
      y_up: True
      normalize: True
      # Prior scale for implicit volume is 0.5 (e.g. geometry.density_blob_std)
      # So we assume the mesh is about the same size
      scale: 0.5

  composed_prompt_processor_type: "deep-floyd-prompt-processor"
  composed_prompt_processor:
    pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
    prompt: ???

  composed_guidance_type: "deep-floyd-guidance"
  composed_guidance:
    pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
    weighting_strategy: uniform
    guidance_scale: 20.
    min_step_percent: 0.02
    max_step_percent: 0.5

  loggers:
    wandb:
      enable: false
      project: "threestudio"

  loss:
    lambda_composed_sds: 0.9
    lambda_composed_individual_sds: 0.05
    lambda_sds: 0.05
    lambda_orient: 0.
    lambda_sparsity: 0.
    lambda_opaque: 0.
    lambda_z_variance: 0.
  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.001
      geometry.feature_network:
        lr: 0.0001
      geometry.sdf:
        lr: 0.001
      geometry.deformation:
        lr: 0.001
      background:
        lr: 0.0001

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 200
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
